Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.InkML;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Win32;
using Npgsql;
using ProyectoRRHH.Models;

namespace ProyectoRRHH.Controllers
{
    [Authorize("RequireAdminRole")]

    public class EmpleadosController : Controller
    {
        private readonly rrhhContext _context;

        public EmpleadosController(rrhhContext context)
        {
            _context = context;
        }

        // GET: Empleados
        public async Task<IActionResult> Index()
        {
            var rrhhContext = _context.empleados
                .Include(e => e.cedulaNavigation)
                .Include(e => e.departamentoNavigation)
                .Include(e => e.puestoNavigation);
            return View(await rrhhContext.ToListAsync());
        }

        //View reporte
        [HttpGet]
        public async Task<IActionResult> Excel()
        {
            var rrhhContext = _context.empleados
                .Include(e => e.cedulaNavigation)
                .Include(e => e.departamentoNavigation)
                .Include(e => e.puestoNavigation);
            return View(await rrhhContext.ToListAsync());
        }

        //Exportar Empleados Excel
        [HttpGet]
        public async Task<FileResult> ExportarEmpleadosAExcel([FromQuery] string fechaInicio, [FromQuery] string fechaFinal)
        {
            DateTime? fechaInicioDate = null;
            DateTime? fechaFinDate = null;

            if (!string.IsNullOrEmpty(fechaInicio))
            {
                fechaInicioDate = DateTime.Parse(fechaInicio);
            }

            if (!string.IsNullOrEmpty(fechaFinal))
            {
                fechaFinDate = DateTime.Parse(fechaFinal);
            }
            var empleados = await _context.empleados
                .Where(e => (!fechaInicioDate.HasValue || e.fechaingreso >= fechaInicioDate.Value) &&
                            (!fechaFinDate.HasValue || e.fechaingreso <= fechaFinDate.Value))
                .ToListAsync();

            //var empleados = await _context.empleados
            //    .Where(e => e.fechaingreso >= fechaInicioDate && e.fechaingreso <= fechaFinDate)
            //    .ToListAsync();

            var nombreArchivo = $"Empleados.xlsx";
            return GenerarExcel(nombreArchivo, empleados);
        }

        //EXCEL
        private FileResult GenerarExcel(string nameArchive, IEnumerable<empleado> empleados)
        {
            DataTable dataTable = new DataTable("empleado");
            dataTable.Columns.AddRange(new DataColumn[]
            {
                new DataColumn("Cedula"),
                new DataColumn("Nombre"),
                new DataColumn("Fecha_Ingreso"),
                new DataColumn("Departamento"),
                new DataColumn("Puesto"),
                new DataColumn("Salario_Mensual"),
                new DataColumn("Estado")
            });

            foreach (var empleado in empleados)
            {
                var row = dataTable.NewRow();
                row["Cedula"] = empleado.cedula;
                row["Nombre"] = empleado.nombre;
                row["Fecha_Ingreso"] = ((DateTime)empleado.fechaingreso).ToString("dd/MM/yyyy");
                row["Departamento"] = empleado.departamento;
                row["Puesto"] = empleado.puesto;
                row["Salario_Mensual"] = empleado.salariomensual;
                row["Estado"] = empleado.estado;

                dataTable.Rows.Add(row);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dataTable);

                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(),
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        nameArchive);
                }

            }

        }
        // GET: Empleados/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.empleados == null)
            {
                return NotFound();
            }

            var empleado = await _context.empleados
                .Include(e => e.cedulaNavigation)
                .Include(e => e.departamentoNavigation)
                .Include(e => e.puestoNavigation)
                .FirstOrDefaultAsync(m => m.id == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleados/Create
        public IActionResult Create()
        {
            ViewData["cedula"] = new SelectList(_context.candidatos, "cedula", "cedula");
            ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1");
            ViewData["puesto"] = new SelectList(_context.puestos, "nombre", "nombre");
            return View();
        }

        // POST: Empleados/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,cedula,nombre,fechaingreso,departamento,puesto,salariomensual,estado")] empleado empleado)
        {
            var fechaingreso = Request.Form["fechaingreso"][0];
            empleado.fechaingreso = DateTime.Parse(fechaingreso);

            var opciones = new List<SelectListItem>
                {
                    new SelectListItem { Value = bool.TrueString, Text = "Activo" },
                    new SelectListItem { Value = bool.FalseString, Text = "Inactivo" }
                };

            ViewBag.estado = opciones;

            try
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                var pgException = ex.InnerException as PostgresException;

                if (pgException != null && pgException.SqlState == "23505")
                {
                    // Handle the duplicate key violation error
                    // Here you can show an error message to the user or take any other action
                    ModelState.AddModelError("Cedula", "La cédula que intenta ingresar ya está registrada.");
                }
                else
                {
                    // Handle other types of DbUpdateException or rethrow the exception
                    throw;
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            if (!ModelState.IsValid)
            {
                ViewData["cedula"] = new SelectList(_context.candidatos, "cedula", "cedula", empleado.cedula);
                ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1", empleado.departamento);
                ViewData["puesto"] = new SelectList(_context.puestos, "nombre", "nombre", empleado.puesto);
                return View(empleado);
            }

            ViewData["cedula"] = new SelectList(_context.candidatos, "cedula", "cedula", empleado.cedula);
            ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1", empleado.departamento);
            ViewData["puesto"] = new SelectList(_context.puestos, "nombre", "nombre", empleado.puesto);
            ViewBag.estado = new SelectList(opciones, "Value", "Text", empleado.estado.ToString());
            return View(empleado);
        }
        // GET: Empleados/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.empleados == null)
            {
                return NotFound();
            }

            var empleado = await _context.empleados.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            ViewData["cedula"] = new SelectList(_context.candidatos, "cedula", "cedula", empleado.cedula);
            ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1", empleado.departamento);
            ViewData["puesto"] = new SelectList(_context.puestos, "nombre", "nombre", empleado.puesto);
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,cedula,nombre,fechaingreso,departamento,puesto,salariomensual,estado")] empleado empleado)
        {
            var fechaingreso = Request.Form["fechaingreso"][0];
            empleado.fechaingreso = DateTime.Parse(fechaingreso);

            var opciones = new List<SelectListItem>
                {
                    new SelectListItem { Value = bool.TrueString, Text = "Activo" },
                    new SelectListItem { Value = bool.FalseString, Text = "Inactivo" }
                };

            if (id != empleado.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);

Controllers/PuestosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoRRHH.Models;

namespace ProyectoRRHH.Controllers
{
    [Authorize("RequireAdminRole")]

    public class PuestosController : Controller
    {
        private readonly rrhhContext _context;

        public PuestosController(rrhhContext context)
        {
            _context = context;
        }

        // GET: puestoes
        public async Task<IActionResult> Index()
        {
              return View(await _context.puestos.ToListAsync());
        }

        // GET: puestoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.puestos == null)
            {
                return NotFound();
            }

            var puesto = await _context.puestos
                .FirstOrDefaultAsync(m => m.id == id);
            if (puesto == null)
            {
                return NotFound();
            }

            return View(puesto);
        }

        // GET: puestoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: puestoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,nombre,nivelriesgo,salariomin,salariomax,estado")] puesto puesto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(puesto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            if (!ModelState.IsValid)
            {
                return View(puesto);
            }
            return View(puesto);
        }

        // GET: puestoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.puestos == null)
            {
                return NotFound();
            }

            var puesto = await _context.puestos.FindAsync(id);
            if (puesto == null)
            {
                return NotFound();
            }
            return View(puesto);
        }

        // POST: puestoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,nombre,nivelriesgo,salariomin,salariomax,estado")] puesto puesto)
        {
            if (id != puesto.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(puesto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!puestoExists(puesto.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(puesto);
        }

        // GET: puestoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.puestos == null)
            {
                return NotFound();
            }

            var puesto = await _context.puestos
                .FirstOrDefaultAsync(m => m.id == id);
            if (puesto == null)
            {
                return NotFound();
            }

            return View(puesto);
        }

        // POST: puestoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.puestos == null)
            {
                return Problem("Entity set 'rrhhContext.puestos'  is null.");
            }
            var puesto = await _context.puestos.FindAsync(id);
            if (puesto != null)
            {
                _context.puestos.Remove(puesto);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool puestoExists(int id)
        {
          return _context.puestos.Any(e => e.id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoRRHH</title>
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
    <link rel="stylesheet" href="~/lib/select2/css/select2-bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    @*    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    *@
    <link rel="stylesheet" href="~/css/csstheme.css" asp-append-version="true" />
   <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/ProyectoRRHH.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoRRHH</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation" fdprocessedid="oy4aq">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>-->
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Competencias" asp-action="Index">Competencias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Departamentos" asp-action="Index">Departamentos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Idiomas" asp-action="Index">Idiomas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Puestos" asp-action="Index">Puestos</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link  text-light dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                Empleados
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item text-white" asp-area="" asp-controller="Empleados" asp-action="Index">Listado</a>
                                    <a class="dropdown-item text-white" asp-area="" asp-controller="Empleados" asp-action="Excel">Reporte</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Candidatos" asp-action="Index">Candidatos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Capacitaciones" asp-action="Index">Capacitaciones</a>
                            </li>
                        }
                        
                        @if (signInManager.IsSignedIn(User) && !User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Candidatos" asp-action="Create">Candidatos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Capacitaciones" asp-action="Create">Capacitaciones</a>
                            </li>

                            @*<li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Candidatos
                                </a>
                                <ul class="dropdown-menu text-light" aria-labelledby="navbarDropdown">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Candidatos" asp-action="Create">Crear</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Capacitaciones
                                </a>
                                <ul class="dropdown-menu text-light" aria-labelledby="navbarDropdown">
                                    <li><a class="nav-link text-dark" asp-area="" asp-controller="Capacitaciones" asp-action="Create">Crear</a></li>
                                </ul>
                            </li>*@
                            
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
@*    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
*@    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Slidebar.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoRRHH</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoRRHH.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap" /></svg>
            <span class="fs-4">Sidebar</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="#" class="nav-link active" aria-current="page">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home" /></svg>
                    Home
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2" /></svg>
                    Dashboard
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table" /></svg>
                    Orders
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid" /></svg>
                    Products
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle" /></svg>
                    Customers
                </a>
            </li>
        </ul>
        <hr>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                <strong>mdo</strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                <li><a class="dropdown-item" href="#">New project...</a></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Sign out</a></li>
            </ul>
        </div>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProyectoRRHH - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>