Controllers/CandidatosController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Drawing;
using DocumentFormat.OpenXml.EMMA;
using DocumentFormat.OpenXml.InkML;
using DocumentFormat.OpenXml.Vml.Office;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoRRHH.Models;

namespace ProyectoRRHH.Controllers
{
    [Authorize]
    public class CandidatosController : Controller
    {
        private readonly rrhhContext _context;

        public CandidatosController(rrhhContext context)
        {
            _context = context;
        }
        [Authorize("RequireAdminRole")]

        // GET: Candidatos
        public async Task<IActionResult> Index()
        {
            var rrhhContext = _context.candidatos
                .Include(c => c.competencia)
                .Include(c => c.idiomas)
                .Include(c => c.departamentoNavigation)
                .Include(c => c.puestoaspiraNavigation);
            return View(await rrhhContext.ToListAsync());
        }
        [Authorize("RequireAdminRole")]

        [HttpGet]
        public async Task<IActionResult> Index(string Candsearch)
        {
            ViewData["candidatos"] = Candsearch;

            var candquery = await _context.candidatos
                .Include(c => c.competencia)
                .Include(c => c.idiomas)
                .Include(c => c.capacitaciones)
                .Include(c => c.departamentoNavigation)
                .Include(c => c.puestoaspiraNavigation).ToListAsync();

            if (candquery.Count < 1)
                return View(candquery);

            var competencias = candquery[0].competencia.ToString();
            var capacitaciones = candquery[0].capacitaciones.ToString();

            if (!string.IsNullOrEmpty(Candsearch))
            {
                candquery = candquery.Where(x => (x.cedula.Contains(Candsearch)) ||
                     x.competencia.Any(c => c.descripcion.ToLower().Trim().Contains(Candsearch.ToLower().Trim())) ||
                     x.capacitaciones.Any(c => c.descripcion.ToLower().Trim().Contains(Candsearch.ToLower().Trim())))
                    .ToList();
            }

            return View(candquery);
        }
        // GET: Candidatos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.candidatos == null)
            {
                return NotFound();
            }

            var candidato = await _context.candidatos
                .Include(c => c.competencia)
                .Include(c => c.idiomas)
                .Include(c => c.departamentoNavigation)
                .Include(c => c.puestoaspiraNavigation)
                .FirstOrDefaultAsync(m => m.id == id);
            if (candidato == null)
            {
                return NotFound();
            }

            return View(candidato);
        }

        // GET: Candidatos/Create
        public IActionResult Create()
        {
            ViewData["competencias"] = new SelectList(_context.competencias, "id", "descripcion");
            ViewData["idiomas"] = new SelectList(_context.idiomas, "id", "nombre");
            ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1");
            ViewData["puestoaspira"] = new SelectList(_context.puestos, "nombre", "nombre");
            return View();
        }

        // POST: Candidatos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,cedula,nombre,puestoaspira,departamento,salarioaspira,explaboral,empresa,puestoocupado,fechadesde,fechahasta,salario,recomendadopor")] candidato candidato)
        {
            var fechadesde = Request.Form["fechadesde"][0];
            candidato.fechadesde = DateTime.Parse(fechadesde);

            var fechahasta = Request.Form["fechahasta"][0];
            candidato.fechahasta = DateTime.Parse(fechahasta);

            if (ModelState.IsValid)
            {
                var competenciasIds = Request.Form["competencia"].Select(x => int.Parse(x)).ToArray();
                var competencias = _context.competencias.Where(x => competenciasIds.Contains(x.id)).ToList();
                candidato.competencia = competencias;

                var idiomasIds = Request.Form["idiomas"].Select(x => int.Parse(x)).ToArray();
                var idiomas = _context.idiomas.Where(x => idiomasIds.Contains(x.id)).ToList();
                candidato.idiomas = idiomas;

                _context.Add(candidato);
                await _context.SaveChangesAsync();

                TempData["Mensaje"] = "¡El registro ha sido guardado correctamente!";

                ViewData["competencias"] = new SelectList(_context.competencias, "id", "descripcion", candidato.competencia);
                ViewData["idiomas"] = new SelectList(_context.idiomas, "id", "nombre", candidato.idiomas);
                ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1", candidato.departamento);
                ViewData["puestoaspira"] = new SelectList(_context.puestos, "nombre", "nombre", candidato.puestoaspira);

                return View(candidato);
            }

            ViewData["competencias"] = new SelectList(_context.competencias, "id", "descripcion", candidato.competencia);
            ViewData["idiomas"] = new SelectList(_context.idiomas, "id", "nombre", candidato.idiomas);
            ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1", candidato.departamento);
            ViewData["puestoaspira"] = new SelectList(_context.puestos, "nombre", "nombre", candidato.puestoaspira);

            return View(candidato);
        }




        // GET: Candidatos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.candidatos == null)
            {
                return NotFound();
            }

            var candidato = await _context.candidatos.FindAsync(id);
            if (candidato == null)
            {
                return NotFound();
            }
            ViewData["competencias"] = new SelectList(_context.competencias, "id", "descripcion", candidato.competencia);
            ViewData["idiomas"] = new SelectList(_context.idiomas, "id", "nombre", candidato.idiomas);
            ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1", candidato.departamento);
            ViewData["puestoaspira"] = new SelectList(_context.puestos, "nombre", "nombre", candidato.puestoaspira);
            return View(candidato);
        }

        // POST: Candidatos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,cedula,nombre,puestoaspira,departamento,salarioaspira,explaboral,empresa,puestoocupado,fechadesde,fechahasta,salario,recomendadopor")] candidato candidato)
        {
            var fechadesde = Request.Form["fechadesde"][0];
            candidato.fechadesde = DateTime.Parse(fechadesde);

            var fechahasta = Request.Form["fechahasta"][0];
            candidato.fechahasta = DateTime.Parse(fechahasta);

            if (id != candidato.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(candidato);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!candidatoExists(candidato.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["competencias"] = new SelectList(_context.competencias, "id", "descripcion", candidato.competencia);
            ViewData["idiomas"] = new SelectList(_context.idiomas, "id", "nombre", candidato.idiomas);
            ViewData["departamento"] = new SelectList(_context.departamentos, "departamento1", "departamento1", candidato.departamento);
            ViewData["puestoaspira"] = new SelectList(_context.puestos, "nombre", "nombre", candidato.puestoaspira);
            return View(candidato);
        }
        [Authorize("RequireAdminRole")]

        // GET: Candidatos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.candidatos == null)
            {
                return NotFound();
            }

            var candidato = await _context.candidatos
                .Include(c => c.competencia)
                .Include(c => c.idiomas)
                .Include(c => c.departamentoNavigation)
                .Include(c => c.puestoaspiraNavigation)
                .FirstOrDefaultAsync(m => m.id == id);
            if (candidato == null)
            {
                return NotFound();
            }

            return View(candidato);
        }

        // POST: Candidatos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.candidatos == null)

Controllers/capacitacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoRRHH.Models;

namespace ProyectoRRHH.Controllers
{
    [Authorize]
    public class CapacitacionesController : Controller
    {
        private readonly rrhhContext _context;

        public CapacitacionesController(rrhhContext context)
        {
            _context = context;
        }
        [Authorize("RequireAdminRole")]

        // GET: Capacitaciones
        public async Task<IActionResult> Index()
        {
            var rrhhContext = _context.capacitaciones.Include(c => c.candidato);
            return View(await rrhhContext.ToListAsync());
        }

        // GET: Capacitaciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.capacitaciones == null)
            {
                return NotFound();
            }

            var capacitacione = await _context.capacitaciones
                .Include(c => c.candidato)
                .FirstOrDefaultAsync(m => m.id == id);
            if (capacitacione == null)
            {
                return NotFound();
            }

            return View(capacitacione);
        }

        // GET: Capacitaciones/Create
        public IActionResult Create()
        {
            ViewData["candidato_id"] = new SelectList(_context.candidatos, "id", "cedula");
            return View();
        }

        // POST: Capacitaciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,candidato_id,descripcion,nivel,fechadesde,fechahasta,institucion")] capacitacione capacitacione)
        {
            var opciones = new List<SelectListItem>
                {
                    new SelectListItem { Value = bool.TrueString, Text = "Bachiller" },
                    new SelectListItem { Value = bool.TrueString, Text = "Bachiller" },
                    new SelectListItem { Value = bool.FalseString, Text = "Técnico" },
                    new SelectListItem { Value = bool.FalseString, Text = "Grado" },
                    new SelectListItem { Value = bool.FalseString, Text = "Postgrado" },
                    new SelectListItem { Value = bool.FalseString, Text = "Maestría" },
                    new SelectListItem { Value = bool.FalseString, Text = "Doctorado" }
                };

            ViewBag.estado = opciones;

            if (!ModelState.IsValid)
            {
                ViewData["candidato_id"] = new SelectList(_context.candidatos, "id", "cedula", capacitacione.candidato_id);
                return View(capacitacione);
            }

            var fechadesde = Request.Form["fechadesde"][0];
            capacitacione.fechadesde = DateTime.Parse(fechadesde);

            var fechahasta = Request.Form["fechahasta"][0];
            capacitacione.fechahasta = DateTime.Parse(fechahasta);

            if (ModelState.IsValid)
            {
                _context.Add(capacitacione);
                await _context.SaveChangesAsync();

                TempData["Mensaje"] = "¡La capacitación ha sido guardada correctamente!";
            }
            ViewBag.estado = new SelectList(opciones, "Value", "Text", capacitacione.nivel.ToString());
            ViewData["candidato_id"] = new SelectList(_context.candidatos, "id", "cedula", capacitacione.candidato_id);
            return View(capacitacione);
        }

        // GET: Capacitaciones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.capacitaciones == null)
            {
                return NotFound();
            }

            var capacitacione = await _context.capacitaciones.FindAsync(id);
            if (capacitacione == null)
            {
                return NotFound();
            }
            ViewData["candidato_id"] = new SelectList(_context.candidatos, "id", "cedula", capacitacione.candidato_id);
            return View(capacitacione);
        }

        // POST: Capacitaciones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,candidato_id,descripcion,nivel,fechadesde,fechahasta,institucion")] capacitacione capacitacione)
        {
            if (id != capacitacione.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(capacitacione);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!capacitacioneExists(capacitacione.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["candidato_id"] = new SelectList(_context.candidatos, "id", "cedula", capacitacione.candidato_id);
            return View(capacitacione);
        }

        // GET: Capacitaciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.capacitaciones == null)
            {
                return NotFound();
            }

            var capacitacione = await _context.capacitaciones
                .Include(c => c.candidato)
                .FirstOrDefaultAsync(m => m.id == id);
            if (capacitacione == null)
            {
                return NotFound();
            }

            return View(capacitacione);
        }

        // POST: Capacitaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.capacitaciones == null)
            {
                return Problem("Entity set 'rrhhContext.capacitaciones'  is null.");
            }
            var capacitacione = await _context.capacitaciones.FindAsync(id);
            if (capacitacione != null)
            {
                _context.capacitaciones.Remove(capacitacione);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool capacitacioneExists(int id)
        {
          return _context.capacitaciones.Any(e => e.id == id);
        }
    }
}

Views/Candidatos/Create.cshtml
@model ProyectoRRHH.Models.candidato

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var mensaje = TempData["Mensaje"] as string;

}
<br />
<h1 class="text-center bg-info-subtle">Candidato</h1>
@if (!string.IsNullOrEmpty(mensaje))
{
    <div class="alert alert-info">@mensaje</div>
}
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           <div class="row">
               <div class="col-md-2"></div>
                <div class="col-md-4">
                    <fieldset>
                        <legend>General:</legend>
                        <div class="form-group mb-2">
                            <label class="control-label">Cédula</label>
                            <input asp-for="cedula" class="form-control" />
                            <span asp-validation-for="cedula" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Nombre</label>
                            <input asp-for="nombre" class="form-control" />
                            <span asp-validation-for="nombre" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Puesto aspiracional</label>
                            <select asp-for="puestoaspira" class="form-control" asp-items="ViewBag.puestoaspira"></select>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Departamento</label>
                            <select asp-for="departamento" class="form-control" asp-items="ViewBag.departamento"></select>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Competencias</label>
                            <select multiple asp-for="competencia" class="form-control" asp-items="ViewBag.competencias"></select>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Idiomas</label>
                            <select multiple asp-for="idiomas" class="form-control" asp-items="ViewBag.idiomas"></select>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Salario aspiracional</label>
                            <input asp-for="salarioaspira" class="form-control" />
                            <span asp-validation-for="salarioaspira" class="text-danger"></span>
                        </div>
                        <br />
                        <hr />
                        <div class="form-group mb-2">
                            <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">Volver</a>
                        </div>

                    </fieldset>
                    </div>
                    <div class="col-md-4">
                        <fieldset class="mb-4">
                            <legend>Experiencia Laboral:</legend>
                            <div class="form-group mb-2">
                            <label class="control-label">Experiencia Laboral</label>
                            <select asp-for="explaboral" class="form-control">
                                <option value="">-Selecciona-</option>
                                <option value="Si">Si</option>
                                <option value="No">No</option>
                            </select>
                                <span asp-validation-for="explaboral" class="text-danger"></span>
                            </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Empresa</label>
                            <input asp-for="empresa" class="form-control" />
                            <span asp-validation-for="empresa" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Puesto ocupado</label>
                            <input asp-for="puestoocupado" class="form-control" />
                            <span asp-validation-for="puestoocupado" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Fecha Desde</label>
                            <input asp-for="fechadesde" class="form-control" type="date" />
                            <span asp-validation-for="fechadesde" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Fecha Hasta</label>
                            <input asp-for="fechahasta" class="form-control" type="date" />
                            <span asp-validation-for="fechahasta" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Salario</label>
                            <input asp-for="salario" class="form-control" />
                            <span asp-validation-for="salario" class="text-danger"></span>
                        </div>
                        <div class="form-group mb-2">
                            <label class="control-label">Recomendado por:</label>
                            <input asp-for="recomendadopor" class="form-control" />
                            <span asp-validation-for="recomendadopor" class="text-danger"></span>
                        </div>
                        <br />
                        <hr />
                        <div class="form-group mb-2">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            <a class="btn btn-primary" asp-area="" asp-controller="Capacitaciones" asp-action="Create">Siguiente</a>

                        </div>
                        </fieldset>
                </div>
                <div class="col-md-2"></div>
            </div>
            <hr />
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $("#competencia").select2({
            theme: "bootstrap"
        })

        $("#idiomas").select2({
            theme: "bootstrap"
        })
    </script>
}

Views/Candidatos/Delete.cshtml
@model ProyectoRRHH.Models.candidato

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<h1 class="text-center">Eliminar</h1>
<div class="alert alert-danger" role="alert">
    Si eliminas este candidato, se elimininará de forma permanente.
</div>
<div
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
        Cédula
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cedula)
        </dd>
        <dt class = "col-sm-2">
        Nombre
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
        Puesto aspiracional
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.salarioaspira)
        </dd>
        <dt class="col-sm-2">
        Competencias
        </dt>
        <dd class="col-sm-10">
            @{
                var competencias = String.Join(", ", Model.competencia.Select(x => x.descripcion).ToArray());
            }
            @Html.DisplayFor(model => competencias)
        </dd>
        <dt class="col-sm-2">
        Idiomas
        </dt>
        <dd class="col-sm-10">
            @{
                var idiomas = String.Join(", ", Model.idiomas.Select(x => x.nombre).ToArray());
            }
            @Html.DisplayFor(model => idiomas)
        </dd>
        <dt class="col-sm-2">
            Departamento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.departamentoNavigation.departamento1)
        </dd>
        <dt class="col-sm-2">
            Puesto aspira
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.puestoaspiraNavigation.nombre)
        </dd>
        <dt class = "col-sm-2">
        Experiencia Laboral
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.explaboral)
        </dd>
        <dt class = "col-sm-2">
        Empresa
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.empresa)
        </dd>
        <dt class = "col-sm-2">
        Puesto ocupado
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.puestoocupado)
        </dd>
        <dt class = "col-sm-2">
        Fecha Desde
        </dt>
        <dd class = "col-sm-10">
            @{
                var fechadesde = ((DateTime)Model.fechadesde).ToString("dd/MM/yyyy");
            }
            @fechadesde
        </dd>
        <dt class = "col-sm-2">
        Fecha Hasta
        </dt>
        <dd class = "col-sm-10">
            @{
                var fechahasta = ((DateTime)Model.fechahasta).ToString("dd/MM/yyyy");
            }
            @fechahasta
        </dd>
        <dt class = "col-sm-2">
        Salario
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.salario)
        </dd>
        <dt class = "col-sm-2">
        Recomendado por:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.recomendadopor)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-primary">Volver</a>
    </form>
</div>

Views/Candidatos/Details.cshtml
@model ProyectoRRHH.Models.candidato

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>candidato</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.salarioaspira)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.salarioaspira)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.explaboral)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.explaboral)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.competencia)
        </dt>
        <dd class="col-sm-10">
            @{
                var competencias = String.Join(", ", Model.competencia.Select(x => x.descripcion).ToArray());
            }
            @Html.DisplayFor(model => competencias)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.idiomas)
        </dt>
        <dd class="col-sm-10">
            @{
                var idiomas = String.Join(", ", Model.idiomas.Select(x => x.nombre).ToArray());
            }
            @Html.DisplayFor(model => idiomas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.empresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.empresa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.puestoocupado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.puestoocupado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fechadesde)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fechadesde)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fechahasta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fechahasta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.recomendadopor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.recomendadopor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.departamentoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.departamentoNavigation.departamento1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.puestoaspiraNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.puestoaspiraNavigation.nombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>